"""add memory lifecycle fields

Revision ID: d58f22a8e1a4
Revises: d7ff51fe128e
Create Date: 2026-07-01 17:28:47.442355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58f22a8e1a4'
down_revision: Union[str, Sequence[str], None] = 'd7ff51fe128e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('status', sa.String(), nullable=True))
    op.add_column('memories', sa.Column('access_count', sa.Integer(), nullable=True))
    op.add_column('memories', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    op.add_column('memories', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('memories', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('memories', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('memories', sa.Column('parent_memory_id', sa.String(), nullable=True))
    op.create_index('idx_memory_lifecycle', 'memories', ['status', 'expires_at'], unique=False)
    op.create_index('idx_memory_user_status', 'memories', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_memories_expires_at'), 'memories', ['expires_at'], unique=False)
    op.create_index(op.f('ix_memories_parent_memory_id'), 'memories', ['parent_memory_id'], unique=False)
    op.create_index(op.f('ix_memories_status'), 'memories', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_status'), table_name='memories')
    op.drop_index(op.f('ix_memories_parent_memory_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_expires_at'), table_name='memories')
    op.drop_index('idx_memory_user_status', table_name='memories')
    op.drop_index('idx_memory_lifecycle', table_name='memories')
    op.drop_column('memories', 'parent_memory_id')
    op.drop_column('memories', 'confidence')
    op.drop_column('memories', 'version')
    op.drop_column('memories', 'expires_at')
    op.drop_column('memories', 'last_accessed_at')
    op.drop_column('memories', 'access_count')
    op.drop_column('memories', 'status')
    # ### end Alembic commands ###
